module PE_chip(
	input				enable_wire,
    input           	dbg_mode_wire,
    input 	[2:0]     	send_num_wire,
    input 	[2:0]     	receive_num_wire,
    input 	[3:0]     	rate_wire,
    input 	[23:0]    	dst_seq_wire,
    input 	[3:0]		mode_wire,
    input               flush_wire,

    output              task_send_finish_flag,
    output              task_receive_finish_flag,

    output	[7:0]       so_retrsreq_receive_flag,
    output 	[7:0]       so_retrsreq_send_flag,
    output 	[7:0]       so_retrsreq_receive_num,
    output 	[7:0]       so_retrsreq_send_num,
    output 	[7:0]       latency_min,
    output 	[7:0]       latency_max,
    output 	[26:0]   	latency_sum,

    output 	[31:0]      data_p2r,
    output              valid_p2r,
    input 	[31:0]      data_r2p,
    input               valid_r2p,
    input               full,

    input               rst_n,
    input       	 	clk
    );

wire				net_enable_wire;
wire           	    net_dbg_mode_wire;
wire 	[2:0]     	net_send_num_wire;
wire 	[2:0]     	net_receive_num_wire;
wire 	[3:0]     	net_rate_wire;
wire 	[23:0]    	net_dst_seq_wire;
wire 	[3:0]		net_mode_wire;
wire               	net_flush_wire;
wire              	net_task_send_finish_flag;
wire              	net_task_receive_finish_flag;
wire	[7:0]       net_so_retrsreq_receive_flag;
wire 	[7:0]       net_so_retrsreq_send_flag;
wire 	[7:0]       net_so_retrsreq_receive_num;
wire 	[7:0]       net_so_retrsreq_send_num;
wire 	[7:0]       net_latency_min;
wire 	[7:0]       net_latency_max;
wire 	[26:0]   	net_latency_sum;
wire 	[31:0]      net_data_p2r;
wire              	net_valid_p2r;
wire 	[31:0]      net_data_r2p;
wire             	net_valid_r2p;
wire              	net_full;
wire              	net_rst_n;
wire       	 		net_clk;

PIW
	PIW_enable_wire(.PAD(enable_wire),.C(net_enable_wire)),
	PIW_dbg_mode_wire(.PAD(dbg_mode_wire),.C(net_dbg_wire)),
	PIW_send_num_wire0(.PAD(send_num_wire[0]),.C(net_send_num_wire[0])),
	PIW_send_num_wire1(.PAD(send_num_wire[1]),.C(net_send_num_wire[1])),
	PIW_send_num_wire2(.PAD(send_num_wire[2]),.C(net_send_num_wire[2])),
	PIW_receive_num_wire0(.PAD(receive_num_wire[0]),.C(net_receive_num_wire[0])),
	PIW_receive_num_wire1(.PAD(receive_num_wire[1]),.C(net_receive_num_wire[1])),
	PIW_receive_num_wire2(.PAD(receive_num_wire[2]),.C(net_receive_num_wire[2])),
	PIW_net_rate_wire0(.PAD(rate_wire[0]),.C(net_rate_wire[0])),
	PIW_net_rate_wire1(.PAD(rate_wire[1]),.C(net_rate_wire[1])),
	PIW_net_rate_wire2(.PAD(rate_wire[2]),.C(net_rate_wire[2])),
	PIW_net_rate_wire3(.PAD(rate_wire[3]),.C(net_rate_wire[3])),
	PIW_net_dst_seq_wire0(.PAD(dst_seq_wire[0]),.C(net_dst_seq_wire[0])),
	PIW_net_dst_seq_wire1(.PAD(dst_seq_wire[1]),.C(net_dst_seq_wire[1])),
	PIW_net_dst_seq_wire2(.PAD(dst_seq_wire[2]),.C(net_dst_seq_wire[2])),
	PIW_net_dst_seq_wire3(.PAD(dst_seq_wire[3]),.C(net_dst_seq_wire[3])),
	PIW_net_dst_seq_wire4(.PAD(dst_seq_wire[4]),.C(net_dst_seq_wire[4])),
	PIW_net_dst_seq_wire5(.PAD(dst_seq_wire[5]),.C(net_dst_seq_wire[5])),
	PIW_net_dst_seq_wire6(.PAD(dst_seq_wire[6]),.C(net_dst_seq_wire[6])),
	PIW_net_dst_seq_wire7(.PAD(dst_seq_wire[7]),.C(net_dst_seq_wire[7])),
	PIW_net_dst_seq_wire8(.PAD(dst_seq_wire[8]),.C(net_dst_seq_wire[8])),
	PIW_net_dst_seq_wire9(.PAD(dst_seq_wire[9]),.C(net_dst_seq_wire[9])),
	PIW_net_dst_seq_wire10(.PAD(dst_seq_wire[10]),.C(net_dst_seq_wire[10])),
	PIW_net_dst_seq_wire11(.PAD(dst_seq_wire[11]),.C(net_dst_seq_wire[11])),
	PIW_net_dst_seq_wire12(.PAD(dst_seq_wire[12]),.C(net_dst_seq_wire[12])),
	PIW_net_dst_seq_wire13(.PAD(dst_seq_wire[13]),.C(net_dst_seq_wire[13])),
	PIW_net_dst_seq_wire14(.PAD(dst_seq_wire[14]),.C(net_dst_seq_wire[14])),
	PIW_net_dst_seq_wire15(.PAD(dst_seq_wire[15]),.C(net_dst_seq_wire[15])),
	PIW_net_dst_seq_wire16(.PAD(dst_seq_wire[16]),.C(net_dst_seq_wire[16])),
	PIW_net_dst_seq_wire17(.PAD(dst_seq_wire[17]),.C(net_dst_seq_wire[17])),
	PIW_net_dst_seq_wire18(.PAD(dst_seq_wire[18]),.C(net_dst_seq_wire[18])),
	PIW_net_dst_seq_wire19(.PAD(dst_seq_wire[19]),.C(net_dst_seq_wire[19])),
	PIW_net_dst_seq_wire20(.PAD(dst_seq_wire[20]),.C(net_dst_seq_wire[20])),
	PIW_net_dst_seq_wire21(.PAD(dst_seq_wire[21]),.C(net_dst_seq_wire[21])),
	PIW_net_dst_seq_wire22(.PAD(dst_seq_wire[22]),.C(net_dst_seq_wire[22])),
	PIW_net_dst_seq_wire23(.PAD(dst_seq_wire[23]),.C(net_dst_seq_wire[23])),
	PIW_net_mode_wire0(.PAD(mode_wire[0]),.C(net_mode_wire[0])),
	PIW_net_mode_wire1(.PAD(mode_wire[1]),.C(net_mode_wire[1])),
	PIW_net_mode_wire2(.PAD(mode_wire[2]),.C(net_mode_wire[2])),
	PIW_net_mode_wire3(.PAD(mode_wire[3]),.C(net_mode_wire[3])),
	PIW_net_flush_wire(.PAD(flush_wire),.C(net_flush_wire)),
	PIW_net_data_r2p0(.PAD(data_r2p[0]),.C(net_data_r2p[0])),
	PIW_net_data_r2p1(.PAD(data_r2p[1]),.C(net_data_r2p[1])),
	PIW_net_data_r2p2(.PAD(data_r2p[2]),.C(net_data_r2p[2])),
	PIW_net_data_r2p3(.PAD(data_r2p[3]),.C(net_data_r2p[3])),
	PIW_net_data_r2p4(.PAD(data_r2p[4]),.C(net_data_r2p[4])),
	PIW_net_data_r2p5(.PAD(data_r2p[5]),.C(net_data_r2p[5])),
	PIW_net_data_r2p6(.PAD(data_r2p[6]),.C(net_data_r2p[6])),
	PIW_net_data_r2p7(.PAD(data_r2p[7]),.C(net_data_r2p[7])),
	PIW_net_data_r2p8(.PAD(data_r2p[8]),.C(net_data_r2p[8])),
	PIW_net_data_r2p9(.PAD(data_r2p[9]),.C(net_data_r2p[9])),
	PIW_net_data_r2p10(.PAD(data_r2p[10]),.C(net_data_r2p[10])),
	PIW_net_data_r2p11(.PAD(data_r2p[11]),.C(net_data_r2p[11])),
	PIW_net_data_r2p12(.PAD(data_r2p[12]),.C(net_data_r2p[12])),
	PIW_net_data_r2p13(.PAD(data_r2p[13]),.C(net_data_r2p[13])),
	PIW_net_data_r2p14(.PAD(data_r2p[14]),.C(net_data_r2p[14])),
	PIW_net_data_r2p15(.PAD(data_r2p[15]),.C(net_data_r2p[15])),
	PIW_net_data_r2p16(.PAD(data_r2p[16]),.C(net_data_r2p[16])),
	PIW_net_data_r2p17(.PAD(data_r2p[17]),.C(net_data_r2p[17])),
	PIW_net_data_r2p18(.PAD(data_r2p[18]),.C(net_data_r2p[18])),
	PIW_net_data_r2p19(.PAD(data_r2p[19]),.C(net_data_r2p[19])),
	PIW_net_data_r2p20(.PAD(data_r2p[20]),.C(net_data_r2p[20])),
	PIW_net_data_r2p21(.PAD(data_r2p[21]),.C(net_data_r2p[21])),
	PIW_net_data_r2p22(.PAD(data_r2p[22]),.C(net_data_r2p[22])),
	PIW_net_data_r2p23(.PAD(data_r2p[23]),.C(net_data_r2p[23])),
	PIW_net_data_r2p24(.PAD(data_r2p[24]),.C(net_data_r2p[24])),
	PIW_net_data_r2p25(.PAD(data_r2p[25]),.C(net_data_r2p[25])),
	PIW_net_data_r2p26(.PAD(data_r2p[26]),.C(net_data_r2p[26])),
	PIW_net_data_r2p27(.PAD(data_r2p[27]),.C(net_data_r2p[27])),
	PIW_net_data_r2p28(.PAD(data_r2p[28]),.C(net_data_r2p[28])),
	PIW_net_data_r2p29(.PAD(data_r2p[29]),.C(net_data_r2p[29])),
	PIW_net_data_r2p30(.PAD(data_r2p[30]),.C(net_data_r2p[30])),
	PIW_net_data_r2p31(.PAD(data_r2p[31]),.C(net_data_r2p[31])),
	PIW_net_valid_r2p(.PAD(valid_r2p),.C(net_valid_r2p)),
	PIW_net_full(.PAD(full),.C(net_full)),
	PIW_net_rst_n(.PAD(rst_n),.C(net_rst_n)),
	PIW_net_clk(.PAD(clk),.C(net_clk));
	

PO8W
	PO8W_task_send_finish_flag(.I(net_task_send_finish_flag),.PAD(task_send_finish_flag)),
	PO8W_task_receive_finish_flag(.I(net_task_receive_finish_flag),.PAD(task_receive_finish_flag)),
	PO8W_so_retrsreq_receive_flag0(.I(net_so_retrsreq_receive_flag[0]),.PAD(so_retrsreq_receive_flag[0])),
	PO8W_so_retrsreq_receive_flag1(.I(net_so_retrsreq_receive_flag[1]),.PAD(so_retrsreq_receive_flag[1])),
	PO8W_so_retrsreq_receive_flag2(.I(net_so_retrsreq_receive_flag[2]),.PAD(so_retrsreq_receive_flag[2])),
	PO8W_so_retrsreq_receive_flag3(.I(net_so_retrsreq_receive_flag[3]),.PAD(so_retrsreq_receive_flag[3])),
	PO8W_so_retrsreq_receive_flag4(.I(net_so_retrsreq_receive_flag[4]),.PAD(so_retrsreq_receive_flag[4])),
	PO8W_so_retrsreq_receive_flag5(.I(net_so_retrsreq_receive_flag[5]),.PAD(so_retrsreq_receive_flag[5])),
	PO8W_so_retrsreq_receive_flag6(.I(net_so_retrsreq_receive_flag[6]),.PAD(so_retrsreq_receive_flag[6])),
	PO8W_so_retrsreq_receive_flag7(.I(net_so_retrsreq_receive_flag[7]),.PAD(so_retrsreq_receive_flag[7])),
	PO8W_so_retrsreq_send_flag0(.I(net_so_retrsreq_send_flag[0]),.PAD(so_retrsreq_send_flag[0])),
	PO8W_so_retrsreq_send_flag1(.I(net_so_retrsreq_send_flag[1]),.PAD(so_retrsreq_send_flag[1])),
	PO8W_so_retrsreq_send_flag2(.I(net_so_retrsreq_send_flag[2]),.PAD(so_retrsreq_send_flag[2])),
	PO8W_so_retrsreq_send_flag3(.I(net_so_retrsreq_send_flag[3]),.PAD(so_retrsreq_send_flag[3])),
	PO8W_so_retrsreq_send_flag4(.I(net_so_retrsreq_send_flag[4]),.PAD(so_retrsreq_send_flag[4])),
	PO8W_so_retrsreq_send_flag5(.I(net_so_retrsreq_send_flag[5]),.PAD(so_retrsreq_send_flag[5])),
	PO8W_so_retrsreq_send_flag6(.I(net_so_retrsreq_send_flag[6]),.PAD(so_retrsreq_send_flag[6])),
	PO8W_so_retrsreq_send_flag7(.I(net_so_retrsreq_send_flag[7]),.PAD(so_retrsreq_send_flag[7])),
	PO8W_so_retrsreq_receive_num0(.I(net_so_retrsreq_receive_num[0]),.PAD(so_retrsreq_receive_num[0])),
	PO8W_so_retrsreq_receive_num1(.I(net_so_retrsreq_receive_num[1]),.PAD(so_retrsreq_receive_num[1])),
	PO8W_so_retrsreq_receive_num2(.I(net_so_retrsreq_receive_num[2]),.PAD(so_retrsreq_receive_num[2])),
	PO8W_so_retrsreq_receive_num3(.I(net_so_retrsreq_receive_num[3]),.PAD(so_retrsreq_receive_num[3])),
	PO8W_so_retrsreq_receive_num4(.I(net_so_retrsreq_receive_num[4]),.PAD(so_retrsreq_receive_num[4])),
	PO8W_so_retrsreq_receive_num5(.I(net_so_retrsreq_receive_num[5]),.PAD(so_retrsreq_receive_num[5])),
	PO8W_so_retrsreq_receive_num6(.I(net_so_retrsreq_receive_num[6]),.PAD(so_retrsreq_receive_num[6])),
	PO8W_so_retrsreq_receive_num7(.I(net_so_retrsreq_receive_num[7]),.PAD(so_retrsreq_receive_num[7])),
	PO8W_so_retrsreq_send_num0(.I(net_so_retrsreq_send_num[0]),.PAD(so_retrsreq_send_num[0])),
	PO8W_so_retrsreq_send_num1(.I(net_so_retrsreq_send_num[1]),.PAD(so_retrsreq_send_num[1])),
	PO8W_so_retrsreq_send_num2(.I(net_so_retrsreq_send_num[2]),.PAD(so_retrsreq_send_num[2])),
	PO8W_so_retrsreq_send_num3(.I(net_so_retrsreq_send_num[3]),.PAD(so_retrsreq_send_num[3])),
	PO8W_so_retrsreq_send_num4(.I(net_so_retrsreq_send_num[4]),.PAD(so_retrsreq_send_num[4])),
	PO8W_so_retrsreq_send_num5(.I(net_so_retrsreq_send_num[5]),.PAD(so_retrsreq_send_num[5])),
	PO8W_so_retrsreq_send_num6(.I(net_so_retrsreq_send_num[6]),.PAD(so_retrsreq_send_num[6])),
	PO8W_so_retrsreq_send_num7(.I(net_so_retrsreq_send_num[7]),.PAD(so_retrsreq_send_num[7])),
	PO8W_latency_min0(.I(net_latency_min[0]),.PAD(latency_min[0])),
	PO8W_latency_min1(.I(net_latency_min[1]),.PAD(latency_min[1])),
	PO8W_latency_min2(.I(net_latency_min[2]),.PAD(latency_min[2])),
	PO8W_latency_min3(.I(net_latency_min[3]),.PAD(latency_min[3])),
	PO8W_latency_min4(.I(net_latency_min[4]),.PAD(latency_min[4])),
	PO8W_latency_min5(.I(net_latency_min[5]),.PAD(latency_min[5])),
	PO8W_latency_min6(.I(net_latency_min[6]),.PAD(latency_min[6])),
	PO8W_latency_min7(.I(net_latency_min[7]),.PAD(latency_min[7])),
	PO8W_latency_max0(.I(net_latency_max[0]),.PAD(latency_max[0])),
	PO8W_latency_max1(.I(net_latency_max[1]),.PAD(latency_max[1])),
	PO8W_latency_max2(.I(net_latency_max[2]),.PAD(latency_max[2])),
	PO8W_latency_max3(.I(net_latency_max[3]),.PAD(latency_max[3])),
	PO8W_latency_max4(.I(net_latency_max[4]),.PAD(latency_max[4])),
	PO8W_latency_max5(.I(net_latency_max[5]),.PAD(latency_max[5])),
	PO8W_latency_max6(.I(net_latency_max[6]),.PAD(latency_max[6])),
	PO8W_latency_max7(.I(net_latency_max[7]),.PAD(latency_max[7])),
	PO8W_latency_sum0(.I(net_latency_sum[0]),.PAD(latency_sum[0])),
	PO8W_latency_sum1(.I(net_latency_sum[1]),.PAD(latency_sum[1])),
	PO8W_latency_sum2(.I(net_latency_sum[2]),.PAD(latency_sum[2])),
	PO8W_latency_sum3(.I(net_latency_sum[3]),.PAD(latency_sum[3])),
	PO8W_latency_sum4(.I(net_latency_sum[4]),.PAD(latency_sum[4])),
	PO8W_latency_sum5(.I(net_latency_sum[5]),.PAD(latency_sum[5])),
	PO8W_latency_sum6(.I(net_latency_sum[6]),.PAD(latency_sum[6])),
	PO8W_latency_sum7(.I(net_latency_sum[7]),.PAD(latency_sum[7])),
	PO8W_latency_sum8(.I(net_latency_sum[8]),.PAD(latency_sum[8])),
	PO8W_latency_sum9(.I(net_latency_sum[9]),.PAD(latency_sum[9])),
	PO8W_latency_sum10(.I(net_latency_sum[10]),.PAD(latency_sum[10])),
	PO8W_latency_sum11(.I(net_latency_sum[11]),.PAD(latency_sum[11])),
	PO8W_latency_sum12(.I(net_latency_sum[12]),.PAD(latency_sum[12])),
	PO8W_latency_sum13(.I(net_latency_sum[13]),.PAD(latency_sum[13])),
	PO8W_latency_sum14(.I(net_latency_sum[14]),.PAD(latency_sum[14])),
	PO8W_latency_sum15(.I(net_latency_sum[15]),.PAD(latency_sum[15])),
	PO8W_latency_sum16(.I(net_latency_sum[16]),.PAD(latency_sum[16])),
	PO8W_latency_sum17(.I(net_latency_sum[17]),.PAD(latency_sum[17])),
	PO8W_latency_sum18(.I(net_latency_sum[18]),.PAD(latency_sum[18])),
	PO8W_latency_sum19(.I(net_latency_sum[19]),.PAD(latency_sum[19])),
	PO8W_latency_sum20(.I(net_latency_sum[20]),.PAD(latency_sum[20])),
	PO8W_latency_sum21(.I(net_latency_sum[21]),.PAD(latency_sum[21])),
	PO8W_latency_sum22(.I(net_latency_sum[22]),.PAD(latency_sum[22])),
	PO8W_latency_sum23(.I(net_latency_sum[23]),.PAD(latency_sum[23])),
	PO8W_latency_sum24(.I(net_latency_sum[24]),.PAD(latency_sum[24])),
	PO8W_latency_sum25(.I(net_latency_sum[25]),.PAD(latency_sum[25])),
	PO8W_latency_sum26(.I(net_latency_sum[26]),.PAD(latency_sum[26])),
	PO8W_data_p2r0(.I(net_data_p2r[0]),.PAD(data_p2r[0])),
	PO8W_data_p2r1(.I(net_data_p2r[1]),.PAD(data_p2r[1])),
	PO8W_data_p2r2(.I(net_data_p2r[2]),.PAD(data_p2r[2])),
	PO8W_data_p2r3(.I(net_data_p2r[3]),.PAD(data_p2r[3])),
	PO8W_data_p2r4(.I(net_data_p2r[4]),.PAD(data_p2r[4])),
	PO8W_data_p2r5(.I(net_data_p2r[5]),.PAD(data_p2r[5])),
	PO8W_data_p2r6(.I(net_data_p2r[6]),.PAD(data_p2r[6])),
	PO8W_data_p2r7(.I(net_data_p2r[7]),.PAD(data_p2r[7])),
	PO8W_data_p2r8(.I(net_data_p2r[8]),.PAD(data_p2r[8])),
	PO8W_data_p2r9(.I(net_data_p2r[9]),.PAD(data_p2r[9])),
	PO8W_data_p2r10(.I(net_data_p2r[10]),.PAD(data_p2r[10])),
	PO8W_data_p2r11(.I(net_data_p2r[11]),.PAD(data_p2r[11])),
	PO8W_data_p2r12(.I(net_data_p2r[12]),.PAD(data_p2r[12])),
	PO8W_data_p2r13(.I(net_data_p2r[13]),.PAD(data_p2r[13])),
	PO8W_data_p2r14(.I(net_data_p2r[14]),.PAD(data_p2r[14])),
	PO8W_data_p2r15(.I(net_data_p2r[15]),.PAD(data_p2r[15])),
	PO8W_data_p2r16(.I(net_data_p2r[16]),.PAD(data_p2r[16])),
	PO8W_data_p2r17(.I(net_data_p2r[17]),.PAD(data_p2r[17])),
	PO8W_data_p2r18(.I(net_data_p2r[18]),.PAD(data_p2r[18])),
	PO8W_data_p2r19(.I(net_data_p2r[19]),.PAD(data_p2r[19])),
	PO8W_data_p2r20(.I(net_data_p2r[20]),.PAD(data_p2r[20])),
	PO8W_data_p2r21(.I(net_data_p2r[21]),.PAD(data_p2r[21])),
	PO8W_data_p2r22(.I(net_data_p2r[22]),.PAD(data_p2r[22])),
	PO8W_data_p2r23(.I(net_data_p2r[23]),.PAD(data_p2r[23])),
	PO8W_data_p2r24(.I(net_data_p2r[24]),.PAD(data_p2r[24])),
	PO8W_data_p2r25(.I(net_data_p2r[25]),.PAD(data_p2r[25])),
	PO8W_data_p2r26(.I(net_data_p2r[26]),.PAD(data_p2r[26])),
	PO8W_data_p2r27(.I(net_data_p2r[27]),.PAD(data_p2r[27])),
	PO8W_data_p2r28(.I(net_data_p2r[28]),.PAD(data_p2r[28])),
	PO8W_data_p2r29(.I(net_data_p2r[29]),.PAD(data_p2r[29])),
	PO8W_data_p2r30(.I(net_data_p2r[30]),.PAD(data_p2r[30])),
	PO8W_data_p2r31(.I(net_data_p2r[31]),.PAD(data_p2r[31])),
	PO8W_valid_p2r(.I(net_valid_p2r),.PAD(valid_p2r));

	
PE insc_PE(
	.enable_wire(net_enable_wire),
    .dbg_mode_wire(net_dbg_mode_wire),
    .send_num_wire(net_send_num_wire),
    .receive_num_wire(net_receive_num_wire),
    .rate_wire(net_rate_wire),
    .dst_seq_wire(net_dst_seq_wire),
    .mode_wire(net_mode_wire),
    .flush_wire(net_flush_wire),

    .task_send_finish_flag(net_task_send_finish_flag),
    .task_receive_finish_flag(net_task_receive_finish_flag),

    .so_retrsreq_receive_flag(net_so_retrsreq_receive_flag),
    .so_retrsreq_send_flag(net_so_retrsreq_send_flag),
    .so_retrsreq_receive_num(net_so_retrsreq_receive_num),
    .so_retrsreq_send_num(net_so_retrsreq_send_num),
    .latency_min(net_latency_min),
    .latency_max(net_latency_max),
    .latency_sum(net_latency_sum),

    .data_p2r(net_data_p2r),
    .valid_p2r(net_valid_p2r),
    .data_r2p(net_data_r2p),
    .valid_r2p(net_valid_r2p),
    .full(net_full),

    .rst_n(net_rst_n),
    .clk(net_clk)
);

endmodule