###################################################################

# Created by write_sdc on Wed Apr 10 19:57:17 2024

###################################################################
set sdc_version 1.8

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_wire_load_mode segmented
set_max_transition 3 [current_design]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports clk]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports rst_n]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {pe_enable[7]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {pe_enable[6]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {pe_enable[5]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {pe_enable[4]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {pe_enable[3]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {pe_enable[2]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {pe_enable[1]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {pe_enable[0]}]
set_load -pin_load 4.37 [get_ports {pe_task_receive_finish_flag[7]}]
set_load -pin_load 4.37 [get_ports {pe_task_receive_finish_flag[6]}]
set_load -pin_load 4.37 [get_ports {pe_task_receive_finish_flag[5]}]
set_load -pin_load 4.37 [get_ports {pe_task_receive_finish_flag[4]}]
set_load -pin_load 4.37 [get_ports {pe_task_receive_finish_flag[3]}]
set_load -pin_load 4.37 [get_ports {pe_task_receive_finish_flag[2]}]
set_load -pin_load 4.37 [get_ports {pe_task_receive_finish_flag[1]}]
set_load -pin_load 4.37 [get_ports {pe_task_receive_finish_flag[0]}]
set_load -pin_load 4.37 [get_ports {pe_task_send_finish_flag[7]}]
set_load -pin_load 4.37 [get_ports {pe_task_send_finish_flag[6]}]
set_load -pin_load 4.37 [get_ports {pe_task_send_finish_flag[5]}]
set_load -pin_load 4.37 [get_ports {pe_task_send_finish_flag[4]}]
set_load -pin_load 4.37 [get_ports {pe_task_send_finish_flag[3]}]
set_load -pin_load 4.37 [get_ports {pe_task_send_finish_flag[2]}]
set_load -pin_load 4.37 [get_ports {pe_task_send_finish_flag[1]}]
set_load -pin_load 4.37 [get_ports {pe_task_send_finish_flag[0]}]
set_ideal_network [get_ports rst_n]
create_clock [get_ports clk]  -period 10  -waveform {0 5}
set_clock_latency 0.3  [get_clocks clk]
set_clock_latency -source 4  [get_clocks clk]
set_clock_uncertainty 0.5  [get_clocks clk]
set_clock_transition -fall 0.2 [get_clocks clk]
set_clock_transition -rise 0.2 [get_clocks clk]
set_input_delay -clock clk  -max 5  [get_ports rst_n]
set_input_delay -clock clk  -max 5  [get_ports {pe_enable[7]}]
set_input_delay -clock clk  -max 5  [get_ports {pe_enable[6]}]
set_input_delay -clock clk  -max 5  [get_ports {pe_enable[5]}]
set_input_delay -clock clk  -max 5  [get_ports {pe_enable[4]}]
set_input_delay -clock clk  -max 5  [get_ports {pe_enable[3]}]
set_input_delay -clock clk  -max 5  [get_ports {pe_enable[2]}]
set_input_delay -clock clk  -max 5  [get_ports {pe_enable[1]}]
set_input_delay -clock clk  -max 5  [get_ports {pe_enable[0]}]
set_output_delay -clock clk  -max 5  [get_ports {pe_task_receive_finish_flag[7]}]
set_output_delay -clock clk  -max 5  [get_ports {pe_task_receive_finish_flag[6]}]
set_output_delay -clock clk  -max 5  [get_ports {pe_task_receive_finish_flag[5]}]
set_output_delay -clock clk  -max 5  [get_ports {pe_task_receive_finish_flag[4]}]
set_output_delay -clock clk  -max 5  [get_ports {pe_task_receive_finish_flag[3]}]
set_output_delay -clock clk  -max 5  [get_ports {pe_task_receive_finish_flag[2]}]
set_output_delay -clock clk  -max 5  [get_ports {pe_task_receive_finish_flag[1]}]
set_output_delay -clock clk  -max 5  [get_ports {pe_task_receive_finish_flag[0]}]
set_output_delay -clock clk  -max 5  [get_ports {pe_task_send_finish_flag[7]}]
set_output_delay -clock clk  -max 5  [get_ports {pe_task_send_finish_flag[6]}]
set_output_delay -clock clk  -max 5  [get_ports {pe_task_send_finish_flag[5]}]
set_output_delay -clock clk  -max 5  [get_ports {pe_task_send_finish_flag[4]}]
set_output_delay -clock clk  -max 5  [get_ports {pe_task_send_finish_flag[3]}]
set_output_delay -clock clk  -max 5  [get_ports {pe_task_send_finish_flag[2]}]
set_output_delay -clock clk  -max 5  [get_ports {pe_task_send_finish_flag[1]}]
set_output_delay -clock clk  -max 5  [get_ports {pe_task_send_finish_flag[0]}]
